services:
  api:
    environment:
      APP_NAME: platform-devops-api
      LOG_LEVEL: info
      OTEL_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318

  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: devops_lab_prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - api
    restart: unless-stopped

  tempo:
    image: grafana/tempo:2.5.0
    container_name: devops_lab_tempo
    user: "0:0"
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./observability/tempo.yaml:/etc/tempo.yaml:ro
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200"
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.103.1
    container_name: devops_lab_otel_collector
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./observability/otel-collector.yaml:/etc/otel-collector.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.4
    container_name: devops_lab_grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
      - tempo
    restart: unless-stopped

volumes:
  prometheus_data:
    name: infra_prometheus_data
  grafana_data:
    name: infra_grafana_data
  tempo_data:
    name: infra_tempo_data
