apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-lab-api-config
  namespace: platform-lab
data:
  NODE_ENV: production
  PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: platform-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/alibayramli/platform-devops-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: platform-lab-api-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: platform-lab-db
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: platform-lab
spec:
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080
